# Generated by Django 4.0.1 on 2022-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_issued_by_ban_issuer_name_ban_issuer_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['discord_id', 'issuer_id', 'variant', 'datetime_start', 'datetime_end'], name='core_ban_discord_bb5c5c_idx'),
        ),
    ]
