# Generated by Django 4.0.1 on 2022-01-16 12:02

import core.utils.time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_issued_by_strike_issuer_name_strike_issuer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='datetime_end',
            field=models.DateTimeField(blank=True, default=core.utils.time.a_month_from_now, help_text='Ban expiry date/time', null=True),
        ),
    ]
