# Generated by Django 4.0.3 on 2022-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_game_datetime_alter_game_datetime_open_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this game or flavour text', max_length=1024),
        ),
    ]
