# Generated by Django 4.0.6 on 2022-09-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_gamechannel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='channel',
        ),
    ]
