# Generated by Django 4.0.6 on 2022-09-26 18:15

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_game_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='dm_rules',
            field=models.TextField(blank=True, help_text='Any banned items / spells, etc', null=True),
        ),
        migrations.AddField(
            model_name='dm',
            name='muster_text',
            field=models.TextField(blank=True, help_text='Default text to add to mustering embed (option)', null=True),
        ),
        migrations.AddIndex(
            model_name='gamechannel',
            index=models.Index(django.db.models.expressions.F('game'), name='gamechannel_game_idx'),
        ),
        migrations.AddIndex(
            model_name='gamechannel',
            index=models.Index(django.db.models.expressions.F('discord_id'), name='gamechannel_discord_idx'),
        ),
    ]
