# Generated by Django 4.0.6 on 2022-10-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dm_muster_text_dm_rules_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm',
            name='muster_text',
            field=models.TextField(blank=True, help_text='Default text to add to mustering embed (option)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='dm',
            name='rules_text',
            field=models.TextField(blank=True, help_text='Any banned items / spells, etc', max_length=1024, null=True),
        ),
    ]
