# Generated by Django 4.0.6 on 2023-01-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_dm_muster_text_alter_dm_rules_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID of player', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='issuer_id',
            field=models.CharField(blank=True, help_text='Discord ID of issuing moderator', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bonuscredit',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID of player', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='bonuscredit',
            name='issuer_id',
            field=models.CharField(blank=True, help_text='Discord ID of issuing moderator', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dm',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID of DM', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID of player', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID of player', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='issuer_id',
            field=models.CharField(blank=True, help_text='Discord ID of issuing moderator', max_length=32, null=True),
        ),
    ]
