# Generated by Django 4.1.1 on 2023-02-23 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_ban_discord_id_alter_ban_issuer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="discord_id",
            field=models.CharField(
                blank=True, help_text="Discord ID of DM", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="dm",
            name="user",
            field=models.ForeignKey(
                help_text="Associated user account",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dm",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
