# Generated by Django 4.1.7 on 2023-03-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_dm_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Discord User', 'verbose_name_plural': 'Discord Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, help_text='Path to the users avatar image', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_discriminator',
            field=models.CharField(blank=True, help_text='Discord discriminator number', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='The discord ID number of the user', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='discord_name',
            field=models.CharField(blank=True, help_text='User name and discriminator', max_length=64, null=True),
        ),
    ]
