# Generated by Django 4.2.3 on 2023-07-05 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='user',
            field=models.ForeignKey(help_text='Associated user account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm', to=settings.AUTH_USER_MODEL),
        ),
    ]
