# Generated by Django 4.2.3 on 2023-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_dm_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Discord User', 'verbose_name_plural': 'Discord Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, help_text='Path to the users avatar image', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord ID of user', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ranks',
            field=models.ManyToManyField(help_text='Ranks held by this user (determined by roles)', related_name='users', to='core.rank'),
        ),
        migrations.AddField(
            model_name='rank',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord role ID number', max_length=32, null=True),
        ),
    ]
