# Generated by Django 4.1.7 on 2023-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='discord_id',
            field=models.BigIntegerField(blank=True, help_text='Discord role ID number', null=True),
        ),
    ]
