# Generated by Django 4.1.7 on 2023-03-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_customuser_options_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='discord_id',
            field=models.CharField(blank=True, help_text='Discord role ID number', max_length=32, null=True),
        ),
    ]
