# Generated by Django 4.2.3 on 2023-07-12 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_customuser_discord_discriminator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrioritySeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=32, null=True)),
                ('purpose', models.CharField(blank=True, max_length=32, null=True)),
                ('locked', models.BooleanField(default=False, help_text='User prevented from modifying')),
                ('datetime_earned', models.DateTimeField(auto_now_add=True, null=True)),
                ('datetime_spent', models.DateTimeField(blank=True, null=True)),
                ('datetime_expiry', models.DateTimeField(blank=True, help_text='When the credit becomes unspendable', null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_credits', to='core.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'game', 'locked', 'origin', 'purpose', 'datetime_expiry', 'datetime_spent'], name='core_credit_owner_i_c3fcbb_idx')],
            },
        ),
    ]
