# Generated by Django 5.0.1 on 2024-01-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_lotteryticket_priorityseat_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='warnings',
            field=models.TextField(blank=True, default='None', help_text='Content warnings or advisories'),
        ),
    ]
