# Generated by Django 5.0.1 on 2024-01-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_game_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_test',
            field=models.BooleanField(default=False, help_text='Set to indicate that this is a playtest'),
        ),
    ]
