# Generated by Django 5.0.1 on 2024-01-19 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_game_play_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechannel',
            name='members',
            field=models.ManyToManyField(related_name='game_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
