# Generated by Django 5.0.1 on 2024-01-24 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_gamechannel_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(help_text='User playing in game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playing', to=settings.AUTH_USER_MODEL),
        ),
    ]
