# Generated by Django 5.0.1 on 2024-02-13 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User playing in game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playing', to=settings.AUTH_USER_MODEL),
        ),
    ]
