# Generated by Django 5.0.1 on 2024-02-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_player_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='core_player_discord_1d11fb_idx',
        ),
        migrations.RemoveField(
            model_name='player',
            name='discord_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='discord_name',
        ),
    ]
