# Generated by Django 5.0.1 on 2024-02-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='length',
            new_name='duration',
        ),
    ]
