# Generated by Django 5.0.1 on 2024-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_length_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(blank=True, default=None, help_text='Planned duration of game (hours)', null=True),
        ),
    ]
