# Generated by Django 5.0.1 on 2024-02-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ready',
            field=models.BooleanField(default=True, help_text='Game is ready for release'),
        ),
    ]
