# Generated by Django 5.0.1 on 2024-06-24 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def migrate_channel_members(apps, schema_editor):
    GameChannel = apps.get_model("core", "gamechannel")
    for channel in GameChannel.objects.all():
        for member in channel.members_old.all():
            channel.members.add(member)

def undo_channel_members(apps, schema_editor):
    GameChannel = apps.get_model("core", "gamechannel")
    for channel in GameChannel.objects.all():
        for member in channel.members.all():
            channel.members_old.add(member)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_game_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='gamechannelmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_messages', models.BooleanField(default=True)),
                ('send_messages', models.BooleanField(default=True)),
                ('read_message_history', models.BooleanField(default=True)),
                ('use_slash_commands', models.BooleanField(default=True)),
                ('manage_messages', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_channel', to='core.gamechannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_channel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(model_name='gamechannel', old_name="members", new_name="members_old"),
       migrations.AddField(
           model_name='gamechannel',
           name='members',
           field=models.ManyToManyField(related_name='game_channels_membership', through='core.gamechannelmember', to=settings.AUTH_USER_MODEL),
       ),
        migrations.RunPython(migrate_channel_members, undo_channel_members),
        migrations.RemoveField(model_name='gamechannel', name='members_old')
    ]
