# Generated by Django 5.0.1 on 2024-07-12 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_gamechannelmember_alter_gamechannel_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamechannel',
            name='members',
            field=models.ManyToManyField(related_name='game_channels', through='core.GameChannelMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic', models.BooleanField(default=False, help_text='Announcement is used as a global fallback')),
                ('text', models.CharField(default='%u joins the game', help_text='Text to use - %u marks where user name is inserted', max_length=256)),
                ('users', models.ManyToManyField(blank=True, help_text='Users this announcement can be used for', related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['text'], name='core_announ_text_a93bcd_idx')],
            },
        ),
    ]
