# Generated by Django 5.0.1 on 2024-08-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_gamechannel_members_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name', max_length=32),
        ),
    ]
