# Generated by Django 5.0.1 on 2024-08-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_gamechannel_members_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.IntegerField(default=4, help_text='Planned duration of game (hours)', null=True),
        ),
    ]
