# Generated by Django 4.1.7 on 2024-09-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_game_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="waitlist",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Rank in queue for place in game",
                null=True,
                verbose_name="Waitlist Position",
            ),
        ),
    ]
