# Generated by Django 5.1.1 on 2024-11-03 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0037_alter_player_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=1, help_text='Credit cost of each ticket')),
                ('ticket_limit', models.IntegerField(default=3, help_text='Max tickets per person')),
                ('max_tickets', models.IntegerField(default=32, help_text='Total number of tickets available')),
                ('datetime_open', models.DateTimeField(blank=True, help_text='Date/Time lottery tickets can be purchased', null=True, verbose_name='Lottery opening date/time')),
                ('datetime_draw', models.DateTimeField(blank=True, help_text='Date/Time lottery is closed and the winners are drawn', null=True, verbose_name='Lottery opening date/time')),
                ('draw_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='credit',
            name='core_credit_owner_i_c3fcbb_idx',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='game',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='purpose',
        ),
        migrations.AddField(
            model_name='credit',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='target_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='lotteryticket',
            name='user',
            field=models.ForeignKey(help_text='Owner of this lottery ticket', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['owner', 'locked', 'origin', 'datetime_expiry', 'datetime_spent'], name='core_credit_owner_i_8d6d59_idx'),
        ),
        migrations.AddField(
            model_name='lottery',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotteries', to='core.game', unique=True),
        ),
        migrations.AddField(
            model_name='lotteryticket',
            name='lottery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.lottery'),
        ),
    ]
