# Generated by Django 5.1.1 on 2024-11-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_game_tabletop_alter_lottery_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='promotion',
            field=models.BooleanField(default=False, help_text='Announcement is used when a player is promoted from waitlist'),
        ),
    ]
