# Generated by Django 5.1.1 on 2024-11-26 21:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_announcement_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMBanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, help_text='Optional notes field for grudge holding', max_length=512, null=True)),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_by', to='core.dm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dm',
            name='banlist',
            field=models.ManyToManyField(related_name='banlisted_by', through='core.DMBanList', to=settings.AUTH_USER_MODEL),
        ),
    ]
