# Generated by Django 5.1.1 on 2024-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_dmbanlist_dm_banlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamechannel',
            name='status',
            field=models.TextField(choices=[('Ready', 'Channel created'), ('Reminder sent', 'Members reminded of game'), ('Warning sent', '1 Hour ping sent'), ('Game started', 'Session summary posted')], default='Ready', help_text='Status of the channel', max_length=32),
        ),
    ]
