# Generated by Django 5.1.1 on 2025-05-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_gamechannel_status"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dm",
            name="core_dm_name_84ef8b_idx",
        ),
        migrations.RemoveField(
            model_name="dm",
            name="discord_id",
        ),
        migrations.RemoveField(
            model_name="dm",
            name="discord_name",
        ),
    ]
