# Generated by Django 4.0 on 2022-01-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='length',
            field=models.CharField(blank=True, default='2 hours', help_text='Planned duration of game', max_length=48),
        ),
    ]
