# Generated by Django 4.0 on 2021-12-31 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='character',
            field=models.ForeignKey(blank=True, help_text='Character info', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.character'),
        ),
        migrations.AlterField(
            model_name='player',
            name='waitlist',
            field=models.IntegerField(help_text='Position in queue for place in game', null=True),
        ),
    ]
