# Generated by Django 4.0 on 2022-01-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_game_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='warnings',
            field=models.TextField(blank=True, default='None', help_text='Content warnings or advisories'),
        ),
    ]
