# Generated by Django 4.0 on 2021-12-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_player_character_alter_player_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='waitlist',
            field=models.IntegerField(blank=True, help_text='Position in queue for place in game', null=True),
        ),
    ]
