# Generated by Django 4.0.1 on 2022-01-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ban_core_ban_discord_bb5c5c_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strike',
            old_name='issued_by',
            new_name='issuer_name',
        ),
        migrations.AddField(
            model_name='strike',
            name='issuer_id',
            field=models.IntegerField(blank=True, help_text='Discord ID of issuing admin', null=True),
        ),
        migrations.AddIndex(
            model_name='strike',
            index=models.Index(fields=['discord_id', 'issuer_id', 'datetime', 'expires'], name='core_strike_discord_db4e3c_idx'),
        ),
    ]
