# Generated by Django 4.0.1 on 2022-01-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ban_datetime_end'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dm',
            index=models.Index(fields=['name', 'discord_id'], name='core_dm_name_84ef8b_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['dm', 'status', 'datetime', 'datetime_release', 'datetime_open_release'], name='core_game_dm_id_080647_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['discord_id', 'game'], name='core_player_discord_1d11fb_idx'),
        ),
        migrations.AddIndex(
            model_name='rank',
            index=models.Index(fields=['priority', 'name'], name='core_rank_priorit_ce4409_idx'),
        ),
    ]
