# Generated by Django 4.0 on 2022-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dm_core_dm_name_84ef8b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='core_game_dm_id_080647_idx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='ready',
            field=models.BooleanField(default=True, help_text='If this game is ready to be published, if this is not set the game will be hidden'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['dm', 'datetime', 'datetime_release', 'datetime_open_release'], name='core_game_dm_id_0fe753_idx'),
        ),
    ]
