# Generated by Django 4.0 on 2022-02-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dm_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='issuer_id',
            field=models.IntegerField(blank=True, help_text='Discord ID of issuing moderator', null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='issuer_name',
            field=models.CharField(help_text='Name of the issuing moderator', max_length=32),
        ),
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.TextField(help_text='Reason for the ban to be issued (mandatory)'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='variant',
            field=models.TextField(choices=[('PM', 'Permanent ban'), ('HD', 'Hard ban'), ('ST', 'Soft ban')], default='HD', help_text="'Hard Ban' removes existing signups, 'Soft' does not", max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='channel',
            field=models.CharField(blank=True, help_text='This field is not yet used', max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(help_text='Date/Time game is starting (your local time)', verbose_name='Game Time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime_open_release',
            field=models.DateTimeField(blank=True, help_text='Date/Time game is released for GENERAL signups (your local time)', null=True, verbose_name='General Release Time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime_release',
            field=models.DateTimeField(blank=True, help_text='Date/Time game is released for PATREON signups (your local time)', null=True, verbose_name='Patreon Release Time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='module',
            field=models.CharField(blank=True, help_text='Adventure Code (e.g. CCC-GHC-09)', max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(help_text='Adventure Name', max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='ready',
            field=models.BooleanField(default=True, help_text='Unset this if the game is not yet ready for release (i.e. still in draft)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='streaming',
            field=models.BooleanField(default=False, help_text='Set to indicate that you may wish to stream the game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='variant',
            field=models.TextField(choices=[('Resident AL', "Resident Adventurer's League"), ('Guest AL DM', "Community DM Adventurer's League"), ('Epic AL', 'Epic Adventurers League'), ('Non-AL One Shot', 'Non-AL One Shot'), ('Campaign', 'Campaign')], default='Resident AL', help_text='Game type', max_length=16),
        ),
        migrations.AlterField(
            model_name='strike',
            name='discord_name',
            field=models.CharField(blank=True, help_text='Player name to receive strike', max_length=32),
        ),
        migrations.AlterField(
            model_name='strike',
            name='issuer_id',
            field=models.IntegerField(blank=True, help_text='Discord ID of issuing moderator', null=True),
        ),
        migrations.AlterField(
            model_name='strike',
            name='issuer_name',
            field=models.CharField(help_text='Name of the issuing moderator', max_length=32),
        ),
    ]
