# Generated by Django 4.0 on 2022-02-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bonuscredit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='standby',
            field=models.BooleanField(default=False, help_text='If player is a waitlist player', verbose_name='Waitlist'),
        ),
        migrations.AlterField(
            model_name='player',
            name='waitlist',
            field=models.IntegerField(blank=True, help_text='Rank in queue for place in game', null=True, verbose_name='Waitlist Position'),
        ),
    ]
