# Generated by Django 4.0 on 2022-02-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_player_standby_alter_player_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='length',
            field=models.CharField(blank=True, default='4 hours', help_text='Planned duration of game', max_length=48),
        ),
    ]
