# Generated by Django 4.0.3 on 2022-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_game_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(help_text='Date/Time game is starting (UTC)', verbose_name='Game Time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime_open_release',
            field=models.DateTimeField(blank=True, help_text='Date/Time game is released for GENERAL signups (UTC)', null=True, verbose_name='General Release Time'),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime_release',
            field=models.DateTimeField(blank=True, help_text='Date/Time game is released for PATREON signups (UTC)', null=True, verbose_name='Patreon Release Time'),
        ),
    ]
