from discord import Embed, Colour

from config.settings import MOONSEACODEX_URL

from discord_bot.moonseacodex.game import Game


class MSCGameJoinEmbed(Embed):
    """Embed to display item advert details from MSC"""

    def __init__(self, game: Game, uuid):
        super().__init__(title=f"Add game to character log")
        self.colour = Colour.purple()

        try:
            self.add_field(name="Name", value=game.name, inline=True)
            self.add_field(name="Module", value=game.module, inline=True)
            self.add_field(name="Date", value=game.date, inline=False)
            self.set_thumbnail(url="https://www.enworld.org/attachments/dd-tashas-1604041136985-jpg.128081/")
            self.add_field(
                name="Moonsea Codex Link",
                value=f"[Click to add this game to a Moonsea Codex character]({MOONSEACODEX_URL}/game/join/{uuid})",
                inline=False,
            )
            self.set_footer(
                text="This embed and the associated MSC game entry are automatically generated by Unseen Servant when a correctly formatted game log is posted to the channel and the DM is a MSC user."
            )
        except Exception as e:
            print(e)
